version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: url-shrt-api
    environment:
      - KV_VIPER_FILE=/app/config.yaml
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./config.yaml:/app/config.yaml
    command: ["run", "service"]
    ports:
      - "8080:8080"

  db:
      image: postgres:latest
      container_name: url-shrt-db
      hostname: url_shrt_db
      environment:
        - POSTGRES_USER=urlshrtuser
        - POSTGRES_PASSWORD=urlshrtpass
        - POSTGRES_DB=url_shortener
        - POSTGRES_HOST_AUTH_METHOD=trust
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U urlshrtuser -d url_shortener"]
        interval: 2s
        timeout: 1s
        retries: 5
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: url-shrt-nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data:
